version: '3.7'
services:
  nginx:
    container_name: lamp-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - type: bind
        source: ../api-server
        target: /var/www/html
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - php
    ports:
      - '8000:80'
      - '4000:443'
  php:
    container_name: lamp-php
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ../api-server:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.33
    container_name: lamp-mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    tty: true

volumes:
  db-store:
